[en]
    languageName = "English"
    contentDir = "content/en"
    weight = 1
    [en.params.head]
        tagline = "Using PENTAtrainer"
    [en.params.feature]
        message = "Comparative prosody modelling across languages"
        tagline = "Welcome to knowledge-transfer website"
        link = "/en/about"
        caption = "About"
    [en.params.footer]
        license = ""
        socialTitle = "Contact us"
        socialCaption = "Feel free to contact us if you have any problems.  Address:The Education University of Hong Kong  Email:prosody@eduhk.hk"

[nl]
    languageName = "Nederlands"
    contentDir = "content/nl"
    weight = 2
    [nl.params.head]
        tagline = "Een Hugo Thema"
    [nl.params.feature]
        message = "Welkom bij Hinode!"
        tagline = "Een documentatie en blog thema voor Hugo gebaseerd op Bootstrap 5."
        link = "/nl/over-mij"
        caption = "Over mij"
    [nl.params.footer]
        license = "Gelicenseerd onder Creative Commons (<a href='https://creativecommons.org/licenses/by-nc-sa/4.0/' class='link-secondary' target='_blank'>CC BY-NC-SA 4.0</a>)."
        socialTitle = "Volg mij"
        socialCaption = "Ik doe aan programmeren en tweet memes"
